In [2]:
import numpy as np
import warnings
import random
import numpy as np
from time import time
from tqdm import tqdm

In [2]:
!pwd

/home/jiwon/recommender_system/HW1-3/Code


In [4]:

from models.UserKNN_explicit import UserKNN
from models.ItemKNN_explicit import ItemKNN
from utils import load_data
dataset = "movielens_100k.csv"
train_data, valid_data, test_data = load_data(dataset, implicit=False)

print('train_data size',train_data)
print('valid_data size',valid_data.shape)
print('test_data size',test_data.shape)

# of users: 943,  # of items: 1682,  # of ratings: 100000
train_data size [[3. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 4. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
valid_data size (943, 1682)
test_data size (943, 1682)


In [5]:
for i,row in enumerate(train_data):
    train_data[i,np.where(row<0.5)[0]] = np.nan
    
user_mean = np.nanmean(train_data,axis=1)
# print(user_mean.shape)
# print(user_mean[0])
# print(np.isnan(user_mean))
user_mean[np.isnan(user_mean)] = 0.0
print(user_mean[:,None].shape)
train = train_data - user_mean[:,None]
print(train.shape)
user_user_sim_matrix = np.zeros((943, 943))
item_item_sim_matrix = np.zeros((1682,1682))

(943, 1)
(943, 1682)


In [10]:
top_k=10
for item_i in tqdm(range(0, 1682), desc='item_item_sim_matrix (k=%d)' % top_k):
    for item_j in range(item_i+1,1682):
        print(item_i)
        print(item_j)
        a = train.T[item_i]
        b = train.T[item_j]
        # print('a',a.shape)
        # print('b',b.shape)
        # print('np.isnan(a)',np.isnan(a))
        # print('np.isnan(b)',np.isnan(b))
        # print('corated',np.logical_or(np.isnan(a),np.isnan(b)))
        # print('corated1',~np.logical_or(np.isnan(a),np.isnan(b)))
        
        co_rated = ~np.logical_or(np.isnan(a),np.isnan(b))
        a = np.compress(co_rated,a)
        b = np.compress(co_rated,b)
        print(a.shape)
        print(b.shape)
        if len(a) == 0:
                continue 

        dot_a_b = np.dot(a, b)
        if dot_a_b == 0:
            continue
        item_item_sim_matrix[item_i, item_j] = dot_a_b / (np.linalg.norm(a) * np.linalg.norm(b))
        print(item_item_sim_matrix)
        assert -1 ==0

item_item_sim_matrix (k=10):   0%|          | 0/1682 [00:00<?, ?it/s]

0
1
(25,)
(25,)
[[0.         0.54784129 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


AssertionError: 

In [6]:
top_k=10
for user_i in tqdm(range(0, 943), desc='user_user_sim_matrix (k=%d)' % top_k):
    for user_j in range(user_i+1,943):
        print(user_i)
        print(user_j)
        a = train[user_i]
        b = train[user_j]
        print('a',a.shape)
        print('b',b.shape)
        print('np.isnan(a)',np.isnan(a))
        print('np.isnan(b)',np.isnan(b))
        print('corated',np.logical_or(np.isnan(a),np.isnan(b)))
        print('corated1',~np.logical_or(np.isnan(a),np.isnan(b)))
        
        co_rated = ~np.logical_or(np.isnan(a),np.isnan(b))
        a = np.compress(co_rated,a)
        b = np.compress(co_rated,b)
        print(a.shape)
        print(b.shape)
        if len(a) == 0:
                continue 

        dot_a_b = np.dot(a, b)
        if dot_a_b == 0:
            continue
        user_user_sim_matrix[user_i, user_j] = dot_a_b / (np.linalg.norm(a) * np.linalg.norm(b))
        print(user_user_sim_matrix.shape)
        assert -1 ==0

user_user_sim_matrix (k=10):   0%|          | 0/943 [00:00<?, ?it/s]

0
1
a (1682,)
b (1682,)
np.isnan(a) [False  True  True ...  True  True  True]
np.isnan(b) [ True  True  True ...  True  True  True]
corated [ True  True  True ...  True  True  True]
corated1 [False False False ... False False False]
(2,)
(2,)
(943, 943)


AssertionError: 